version: "3.7"

services:
  php:
    container_name: treinamento-api_php
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    restart: always
    volumes:
      - .:/application
    networks:
      - app-gateway

  treinamento-api_nginx:
    container_name: treinamento-api_nginx
    hostname: treinamento-api_nginx
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    environment:
      NGINX_HOST: treinamento-api.localhost
      PHP_FPM_HOST: treinamento-api_php
    volumes:
      - .:/application
    ports:
       - "8100:80"
    depends_on: 
      - php
    networks:
      - app-gateway

networks:
  app-gateway:
    external: true