version: "3.7"

services:
  php:
    container_name: treinamento-api_php
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    restart: always
    volumes:
      - .:/application

  nginx:
    container_name: treinamento-api_nginx
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    environment:
      NGINX_HOST: treinamento-api.localhost
      PHP_FPM_HOST: treinamento-api_php
    volumes:
      - .:/application
    depends_on: 
      - php
